ExcelExtractor/Models/ExcelDatum.cs
using System;
using System.Collections.Generic;

namespace ExcelExtractor.Models;

public partial class ExcelDatum
{
    public int Id { get; set; }

    public string ExcelName { get; set; }

    public string ExcelValue { get; set; }

    public string CreatedOn { get; set; }
}

ExcelExtractor/ViewModels/ExcelModel.cs
namespace ExcelExtractor.ViewModels
{
    public class ExcelModel
    {
        public string ExcelName { get; set; }
        public string ExcelValue { get; set; }
    }
}

ExcelExtractor/Controllers/ExtractorController.cs
using ExcelExtractor.Manager.Interface;
using ExcelExtractor.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace ExcelExtractor.Controllers
{
    public class ExtractorController : Controller
    {
        private readonly IExtractorService _extractorService;

        public ExtractorController(IExtractorService extractorService)
        {
            _extractorService = extractorService;
        }

        [HttpGet]
        public IActionResult Home()
        {
			try
			{
				return View();
			}
			catch (Exception)
			{
				throw;
			}
        }

        [HttpPost]
        public async Task<IActionResult> Home(List<ExcelModel> model)
        {
            try
            {
                await _extractorService.SaveExcel(model);

                return View();
            }
            catch (Exception)
            {
                throw;
            }
        }
    }
}

ExcelExtractor/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ExcelExtractor.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ExcelExtractor/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ExcelExtractor.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

ExcelExtractor/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ExcelExtractor.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ExcelExtractor/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<!DOCTYPE html>
<html>
<head>
    <title>Extract data from Excel file using JavaScript</title>
</head>
<body>
    @*<input type="file" id="fileInput1" accept=".xlsx" />*@
    <input type="file" webkitdirectory id="ImportFiles">
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.16.9/xlsx.full.min.js"></script>
    the online version.-->
  
</body>
</html>

@section Scripts{
    <script src="~/js/site.js"></script>
    <script src="~/js/scriptpre.js"></script>
}

ExcelExtractor/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExcelExtractor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExcelExtractor.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ExcelExtractor</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Extractor" asp-action="Home">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ExcelExtractor - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>